
- name: create folder
  file:
    path: "~/Documents/ansible_textfiles"
    state: directory

- name: create five text files
  copy:
    content: "{{ item.content }}"
    dest: "~/Documents/ansible_textfiles/{{ item.filename }}"
  loop:
    - { filename: 'file1.txt', content: '{{ message_file_1 }}' }
    - { filename: 'file2.txt', content: 'Inhalt der Datei 2' }
    - { filename: 'file3.txt', content: '{{ message_file_3 }}' }
    - { filename: 'file4.txt', content: 'Inhalt der Datei 4' }
    - { filename: 'file5.txt', content: 'Inhalt der Datei 5' }

- name: Replace text in line 2 of two text files
  lineinfile:
    path: "~/Documents/ansible_textfiles/{{ item }}"
    regexp: '^.*$'
    line: 'Lorem Ipsum'
    state: present
    insertafter: '^.*$'
  loop:
    - file1.txt
    - file2.txt

- name: Run tree command
  command: tree
  register: tree_output

- name: Display tree command output
  debug:
    var: tree_output.stdout_lines

- name: Print message
  debug:
    msg: "{{ message }}"
